# -*- coding: utf-8 -*-
"""Predict Calories Expenditure

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i2MsRZNMNz75m5ukWAAbsAQlXj5BIyqu

# Calories Counter Project

## Imports
"""

from packaging import version
from sklearn.preprocessing import OrdinalEncoder
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_val_score
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import VotingRegressor
from sklearn.linear_model import Ridge
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR


import sklearn
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

assert version.parse(sklearn.__version__) >= version.parse("1.0.1")

"""##Helper Function"""

def rmsle(y_true, y_pred):
    return np.sqrt(mean_squared_error(np.log1p(y_true), np.log1p(y_pred)))
def evaluation(model,X_test, y_test):
  y_pred = model.predict(X_test)

  y_pred = np.abs(y_pred)

  # Evaluate the performance using a suitable metric, e.g., Root Mean Squared Error (RMSE)

  rmse = mean_squared_error(y_test, y_pred)
  rmsle_val = rmsle(y_test, y_pred)

  print(f"RMSE on the test set: {rmse}")
  print(f"RMSLE on the test set: {rmsle_val}")

  # You can also visualize the predictions vs actual values
  plt.figure(figsize=(10, 6))
  plt.scatter(y_test, y_pred, alpha=0.5)
  plt.xlabel("Actual Calories")
  plt.ylabel("Predicted Calories")
  plt.title("Actual vs. Predicted Calories (Test Set)")
  plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'k--', lw=2) # Diagonal line
  plt.show()

def save_submission_file(model):
  sample_submission_path = f'{unzip_directory}/sample_submission.csv'
  # Load the sample_submission.csv file
  submission_df = pd.read_csv(sample_submission_path)

  # Ensure the test_df has the same columns as the training data (excluding the target 'Calories')
  # and in the same order, before making predictions.
  # Assuming X_train contains the columns used for training.
  test_df_aligned = test_df[X_train.columns]

  # Make predictions on the aligned test data using the trained pipeline
  test_predictions = model.predict(test_df_aligned)

  # Since calories cannot be negative, ensure predictions are non-negative
  test_predictions = np.abs(test_predictions)

  # Replace the 'Calories' column in the submission DataFrame with the predictions
  submission_df['Calories'] = test_predictions.round().astype(int) # Round and convert to integer if appropriate

  # Display the first few rows of the updated submission DataFrame
  print(submission_df.head())

  # Save the updated submission DataFrame to a new CSV file (or overwrite the original)
  # For example, to a new file:
  # output_submission_path = f'{unzip_directory}/submission_with_predictions.csv'
  # submission_df.to_csv(output_submission_path, index=False)

  # Or to overwrite the original:
  submission_df.to_csv(sample_submission_path, index=False)

  print(f"Predictions saved to {sample_submission_path}")

"""## Download Data"""

# prompt: help me download and unzip the following shared file: https://drive.google.com/file/d/1S8YoUUNWUWXebWfssg9wHRNB-y1s_ZNh/view?usp=drive_link
# https://drive.google.com/file/d/1S8YoUUNWUWXebWfssg9wHRNB-y1s_ZNh/view?usp=sharing
# Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

# Download the file from Google Drive
# You need to replace 'FILE_ID' with the actual file ID from the link.
# The file ID is the part after /d/ and before /view
# For the provided link: 1S8YoUUNWUWXebWfssg9wHRNB-y1s_ZNh
file_id = '1S8YoUUNWUWXebWfssg9wHRNB-y1s_ZNh'
download_path = '/content/downloaded_file.zip' # You can change the filename

!gdown --id {file_id} -O {download_path}

# Unzip the downloaded file
unzip_directory = '/content/unzipped_content' # Directory to unzip to
!mkdir -p {unzip_directory} # Create the directory if it doesn't exist
!unzip {download_path} -d {unzip_directory}

# List the contents of the unzipped directory to verify
!ls {unzip_directory}

"""## Data Exploration"""

# Define the path to the train.csv file within the unzipped directory
train_data_path = f'{unzip_directory}/train.csv'

# Load the train.csv file into a pandas DataFrame
train_df = pd.read_csv(train_data_path)

"""### Take a Quick Look at the Data Structure"""

# Display the first few rows of the DataFrame to verify
print(train_df.head())

print(train_df.info())

train_df["Sex"].value_counts()

train_df.describe()

plt.rc('font', size=14)
plt.rc('axes', labelsize=14, titlesize=14)
plt.rc('legend', fontsize=14)
plt.rc('xtick', labelsize=10)
plt.rc('ytick', labelsize=10)

train_df.hist(bins=50, figsize=(20,15))
plt.show()

"""To ensure that the outputs are consistent, random seed will be set"""

np.random.seed(42)

"""### Correlation Analysis"""

corr_matrix = train_df.corr(numeric_only=True)

#Correlation with heart rate
corr_matrix["Heart_Rate"].sort_values(ascending=False)

#Correlation with weight
corr_matrix["Weight"].sort_values(ascending=False)

#Correlation with age
corr_matrix["Age"].sort_values(ascending=False)

#Correlation with duration
corr_matrix["Duration"].sort_values(ascending=False)

#Correlation with calories
corr_matrix["Calories"].sort_values(ascending=False)

#Correlation with height
corr_matrix["Height"].sort_values(ascending=False)

"""## Cleaning the Data"""

#Changing sex category from female and male to 0 and 1, respectively
ordinal_encoder = OrdinalEncoder()
sex_cat = train_df[["Sex"]]
sex_encoded = ordinal_encoder.fit_transform(sex_cat)

#Checking the data
sex_encoded[:10]
#ordinal_encoder.categories_
#train_df.head()

# prompt: replace the sex category with the encoded values (0,1)

train_df["Sex"] = sex_encoded
train_df.head()

train_set, test_set = train_test_split(train_df, test_size=0.2, random_state=42)

train_set

"""## Training the Baseline"""

# prompt: split the pandas into a trianing set x and a label y, where labels are the calories

X_train = train_set.drop("Calories", axis=1)
y_train = train_set["Calories"].copy()

X_train.shape, y_train.shape

#y[:10]

X_test = test_set.drop("Calories", axis=1)
y_test = test_set["Calories"].copy()

X_test.shape, y_test.shape

lin_reg = LinearRegression()
lin_reg.fit(X_train,y_train)

lin_rmses = -cross_val_score(lin_reg, X_train, y_train,
                              scoring="neg_root_mean_squared_error", cv=10)
pd.Series(lin_rmses).describe()

"""## Evaluate the Test Set"""

# prompt: please help me load the test set "test.csv" from the folder "unzipped_content"

# Define the path to the test.csv file within the unzipped directory
test_data_path = f'{unzip_directory}/test.csv'

# Load the test.csv file into a pandas DataFrame
test_df = pd.read_csv(test_data_path)

# Display the first few rows of the test DataFrame to verify
print(test_df.head())
print(test_df.info())

sex_cat_test = test_df[["Sex"]]
sex_encoded_test = ordinal_encoder.fit_transform(sex_cat_test)

test_df["Sex"] = sex_encoded_test
test_df.head()

"""##Improvement 1 Feature Scaling"""

pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('regressor', LinearRegression())
])
pipeline.fit(X_test, y_test)

evaluation(pipeline,X_test, y_test)

# Define the path to the test.csv file within the unzipped directory
test_data_path = f'{unzip_directory}/test.csv'

# Load the test.csv file into a pandas DataFrame
test_df = pd.read_csv(test_data_path)

# Display the first few rows of the test DataFrame to verify
print(test_df.head())
print(test_df.info())

sex_cat_test = test_df[["Sex"]]
sex_encoded_test = ordinal_encoder.fit_transform(sex_cat_test)
print(sex_encoded_test[:10])

test_df["Sex"] = sex_encoded_test
test_df.head()

save_submission_file(pipeline)

"""## Improvement: Use a Decision Tree or Random Forest"""

tree_reg = DecisionTreeRegressor(random_state=42)
tree_reg.fit(X_train, y_train)

evaluation(tree_reg,X_test, y_test)

save_submission_file(tree_reg)

forest_reg = RandomForestRegressor(random_state=42)
forest_reg.fit(X_train, y_train)

"""##Improvement 2 - Forest Regression Evaluation"""

evaluation(forest_reg,X_test, y_test)

save_submission_file(forest_reg)

"""## Improvement 3 - Grid Search"""

full_pipeline = Pipeline([

    ("random_forest", RandomForestRegressor(random_state=42)),
])
param_grid = [
    {
     'random_forest__max_features': [2, 3, 4, 5, 6]}
]
grid_search = GridSearchCV(full_pipeline, param_grid, cv=3,
                           scoring='neg_root_mean_squared_error')
grid_search.fit(X_train, y_train)



"""##Improvement 4 - Feature Engineering"""

# prompt: I want to add a new feature to the data set, which is BMI (BMI = weight / height², where weight is in kilograms and weight is in meters

train_df["BMI"] = train_df["Weight"] / (train_df["Height"] / 100)**2
test_df["BMI"] = test_df["Weight"] / (test_df["Height"] / 100)**2

train_set, test_set = train_test_split(train_df, test_size=0.2, random_state=42)

X_train = train_set.drop("Calories", axis=1)
y_train = train_set["Calories"].copy()

X_test = test_set.drop("Calories", axis=1)
y_test = test_set["Calories"].copy()

X_train.shape, y_train.shape
X_test.shape, y_test.shape

# prompt: confirm that the data include bmi print it

# Verify that the 'BMI' column was added to the DataFrame
print(train_df.head())

# Print information about the DataFrame including the new 'BMI' column
#print(train_df.info())

forest_reg = RandomForestRegressor(random_state=42)
forest_reg.fit(X_train, y_train)

evaluation(forest_reg, X_test, y_test)
save_submission_file(forest_reg)

# prompt: suggest a feature to see if there's a ratio between duration and heart rate. also suggest a feature that corresponds to the intensity based on the heart rate and the duration

train_df['Heart_Rate_Duration_Ratio'] = train_df['Heart_Rate'] / train_df['Duration']
test_df['Heart_Rate_Duration_Ratio'] = test_df['Heart_Rate'] / test_df['Duration']

# prompt: create a feature of heart rate times duration to allow curvature

train_df['Heart_Rate_Duration_Squared'] = (train_df['Heart_Rate'] * train_df['Duration'])**2
test_df['Heart_Rate_Duration_Squared'] = (test_df['Heart_Rate'] * test_df['Duration'])**2

X_train = train_set.drop("Calories", axis=1)
y_train = train_set["Calories"].copy()

X_test = test_set.drop("Calories", axis=1)
y_test = test_set["Calories"].copy()

# prompt: create a new feature of body temp and heart rate ratio

train_df['Body_Temp_Heart_Rate_Ratio'] = train_df['Body_Temp'] / train_df['Heart_Rate']
test_df['Body_Temp_Heart_Rate_Ratio'] = test_df['Body_Temp'] / test_df['Heart_Rate']

# Update the X_train and X_test DataFrames to include the new feature
# It's important to ensure X_train and X_test reflect the features used in the pipeline/model training
# If the subsequent steps will use X_train and X_test directly, update them here.
# If they will use the full train_df and test_df with a pipeline, the previous steps adding columns to train_df/test_df are sufficient.

# For example, if you rebuild X_train and X_test:
X_train = train_df.drop("Calories", axis=1)
y_train = train_df["Calories"].copy()

X_test = test_df.drop("Calories", axis=1)
y_test = test_df["Calories"].copy()

print("Updated X_train with new feature:")
print(X_train.head())
print("\nUpdated X_test with new feature:")
print(X_test.head())

"""## Improvement 5 - Ensemble Learning"""

# 1. Instantiate your chosen regressors
reg1 = Ridge(alpha=1.0)
reg2 = RandomForestRegressor(n_estimators=100, random_state=42)
reg3 = SVR(kernel='rbf', C=100)

# 2. Create the VotingRegressor
# The 'estimators' argument is a list of tuples, where each tuple contains
# a name for the regressor and the regressor object itself.
voting_regressor = VotingRegressor(
    estimators=[('ridge', reg1), ('rf', reg2), ('svr', reg3)]
)

# 3. Fit the model on your training data
voting_regressor.fit(X_train, y_train)

# 4. Make predictions
#  predictions = voting_regressor.predict(X_test)